### PR TITLE
Added CMakeLists

### PR DESCRIPTION
**Pull request by ZetaTwo**
Added a CMakeLists file for compiling with CMake

### CODE REVIEW

**Comment by upbit** [comment]
Thanks for the contribution.

**Comment by ZetaTwo** [comment]
No problem. Thanks for a nice tool.

**Comment by upbit** [comment]
I'am not the writer.
[HashClash](http://www.win.tue.nl/hashclash/) started as Marc Stevens' TU/e Master Degree project, I just fork from the website :)

**Comment by ZetaTwo** [comment]
Well, a big thanks to him then. :D

**Pull request merged**
